		<!-- <link rel="stylesheet" type="text/css" href="assets/css/authorized_style.css"> -->
    </head>

    <body>

		<div class="l-grid-dashboard content-width">

			<div id="dashboard_header" class="l-grid-header color-header">
			</div>

			<div id="dashboard_menu" class="l-grid-menu color-menu">
				<div class="menu-button-position">
					<a href="http://portal.bsod.space/" class="menu-button">Главная</a>
				</div>
				<div class="menu-button-position">
					<a href="http://portal.bsod.space/dashboard/refresh" class="menu-button">Обновить</a>
				</div>
				<div class="menu-button-position">
					<a href="http://portal.bsod.space/logout" class="menu-button">Выход</a>
				</div>
			</div>

			<div id="dashboard_main" class="l-grid-main color-main color-dashboard-services">

				<div id="dashboard_content" class="l-grid-dashboard-services">

					<div class="l-dashboard-services color-main">

						<div>
							<p style="text-align:center">
								Discord Service:
								<div class="l-services-buttons-box">
									<?php if ($discord_auth_state == "no") : ?>
										<a href="<?= $discord_url; ?>" class="menu-button">Активировать</a>
									<?php else: ?>
										<a href="http://portal.bsod.space/discord/deactivate" class="menu-button">Деактивировать</a>
									<?php endif; ?>
								</div>
							</p>
						</div>

						<div>
							<p style="text-align:center">
								Teamspeak Service:
								<div class="l-services-buttons-box">
									<?php if (!isset($teamspeak_token)) : ?>
										<a href="http://portal.bsod.space/teamspeak/activate" class="menu-button">Активировать</a>
									<?php else: ?>
										<a href="http://portal.bsod.space/teamspeak/deactivate" class="menu-button">Деактивировать</a>
									<?php endif; ?>
								</div>
								<?php if (isset($teamspeak_token)) : ?>
									<div class="l-services-buttons-box">
											<a href="ts3server://<?= $teamspeak_url; ?>?token=<?= $teamspeak_token; ?>&nickname=<?= $teamspeak_nick; ?>" class="menu-button">Войти в TS3</a>
									</div>
								<?php else: ?>
								<?php endif; ?>
							</p>
						</div>

						<div>
							<p style="text-align:center">
								Forum Service:
								<div class="l-services-buttons-box">
									<?php if (!isset($teamspeak_token)) : ?>
										<a href="http://portal.bsod.space/dashboard" class="menu-button">Активировать</a>
									<?php else: ?>
										<a href="http://portal.bsod.space/dashboard" class="menu-button">Деактивировать</a>
									<?php endif; ?>
								</div>
							</p>
						</div>

						<?php if ($is_admin) : ?>
							<div>
								<p style="text-align:center">
									Add custom tokens:
									<div class="l-services-buttons-box">
										<a href="http://portal.bsod.space/login/contacts" class="menu-button">Add Contacts Token</a>
									</div>
								</p>
							</div>
						<?php endif; ?>

					</div>

					<div class="l-dashboard-infopanel color-main">
						<div class="l-dashboard-avatar-box">
							<p style="text-align:center">
								<!-- <img width="256px" height="256px" src="https://imageserver.eveonline.com/Character/_256.jpg" alt="CharAvatar"> -->
								<?php if (isset($character_id)) : ?>
									<picture>
										<img src="https://imageserver.eveonline.com/Character/<?= $character_id; ?>_256.jpg" alt="CharAvatar">
									</picture>
								<?php else: ?>
									Something wrong!
								<?php endif; ?>
							</p>
						</div>
						<div>
							<p style="text-align:left">
								Your main char is: <?= $char_name; ?><br>
								Your Corporation: <?= $corp_name; ?><br>
								Your Alliance: <?= $alliance_name; ?><br>
							</p>
						</div>
					</div>

				</div>

			</div>

			<div id="dashboard_footer" class="l-grid-footer color-footer">
			</div>

		</div>

    </body>
