    </head>
	<body>

		<div class="l-grid-root content-width">

			<div class="l-grid-main color-main">

				<div class="l-root-logo-box">
					<img src="assets/img/bsod-logo.png" alt="Logo">
				</div>
				
				<div class="l-root-buttons-box">

					<div class="menu-button-position">
						<a href="http://portal.bsod.space/dashboard" class="menu-button">Dashboard</a>
					</div>

					<div class="menu-button-position">
						<a href="http://portal.bsod.space/forum" class="menu-button">Forum</a>
					</div>

					<div class="menu-button-position">
						<a href="http://portal.bsod.space/dashboard" class="menu-button">Killboard</a>
					</div>

				</div>

			</div>
			
		</div>

	</body>
