    </head>
	<body>

		<div class="l-grid-root content-width">

			<div class="l-grid-main color-main">

				<div class="l-root-logo-box">
					<img src="assets/img/bsod-logo.png" alt="Logo">
				</div>

				<div class="l-root-buttons-box">
					<p style="text-align:center" class="lead">
						Click the button below to login with your EVE Online account.
					</p>
					<p>
						<a href="<?= $ssoURL; ?>">
							<img src="https://images.contentful.com/idjq7aai9ylm/4fSjj56uD6CYwYyus4KmES/4f6385c91e6de56274d99496e6adebab/EVE_SSO_Login_Buttons_Large_Black.png"/>
						</a>
					</p>
				</div>

			</div>

		</div>

	</body>
