<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link rel="apple-touch-icon" sizes="57x57" href="static/img/favicon/apple-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="static/img/favicon/apple-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="static/img/favicon/apple-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="static/img/favicon/apple-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="static/img/favicon/apple-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="static/img/favicon/apple-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="static/img/favicon/apple-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="static/img/favicon/apple-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="static/img/favicon/apple-icon-180x180.png">
		<link rel="icon" type="image/png" sizes="192x192"  href="static/img/favicon/android-icon-192x192.png">
		<link rel="icon" type="image/png" sizes="32x32" href="static/img/favicon/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="96x96" href="static/img/favicon/favicon-96x96.png">
		<link rel="icon" type="image/png" sizes="16x16" href="static/img/favicon/favicon-16x16.png">
		<link rel="manifest" href="static/img/favicon/manifest.json">
		<meta name="msapplication-TileColor" content="#ffffff">
		<meta name="msapplication-TileImage" content="static/img/favicon/ms-icon-144x144.png">
		<meta name="theme-color" content="#ffffff">

        <title>Bright Side of Death</title>
		<link rel="stylesheet" type="text/css" href="static/css/test.css">
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    </head>
    <body>
		<div id="logo">
			<p style="text-align:center">
				<img width="240px" height="240px" src="static/img/bsod-logo.png" alt="Logo">
			</p>
		</div>
		<div id="content">
			<p style="text-align:center" class="lead">
				Click the button below to login with your EVE Online account.
			</p>
			<p>
				<a href="http://bsod.space">
					<img src="https://images.contentful.com/idjq7aai9ylm/4fSjj56uD6CYwYyus4KmES/4f6385c91e6de56274d99496e6adebab/EVE_SSO_Login_Buttons_Large_Black.png"/>
				</a>
			</p>
		</div>
    </body>
</html>
